### PR TITLE
Option to much slower but little bit more exact latency result

### PR DESCRIPTION
**Pull request by kanocz**
Option to don't use threaded icmp sending... in case of large numbers of IPs (more than 64k) i get more answers and more realistic latency time. But we lost about 20% of sending speed in this case.

### CODE REVIEW

**Comment by tatsushid** [comment]
I guess the latency problem is caused by the timing of calling `time.Now` and `WaitGroup` in `sendICMP` so refactoring `sendICMP` and `run` may improve both the latency and packet sending slowness.

**Comment by kanocz** [comment]
Hm... you're right... and executing goroutine for every packet send is also overkill - if i'm trying to send 16M pings it's really doing bad things :)

**Comment by tatsushid** [comment]
> executing goroutine for every packet send is also overkill
It's considerable point. Original AnyEvent::FastPing splits into 256 addresses (/24 segment size) per thread and fping does it in single event loop.

**Comment by kanocz** [comment]
256 ips chunks soudns good... but also be good to limit number of threads to something like NUMCPU*2 or NUMCPU*4

**Comment by tatsushid** [comment]
I rewrite the `sendICMP` function in a following way

- Use multiples of GOMAXPROCS goroutines instead of goroutines as same numbers as hosts
- Each goroutines marshals an ICMP packet and sends it. It should show more accurate latency time.

This is not merged into mainline but available at [fix/refactor-sendicmp](https://github.com/tatsushid/go-fastping/tree/fix/refactor-sendicmp) branch. Can you test it in your large number of hosts environment?

The number of concurrency is defined in `numGoRoutines` so you can test different number of it by changing it.

**Comment by kanocz** [comment]
thank you! i'll test it today

**Comment by kanocz** [comment]
It seems that on 24-core server maximal count of IPs with relevant latency result is about 16-20k with this patch (much better than in original version), but it's also seems that bottleneck is now receiver thread which is only one for all sending threads... maybe we can use more receiver threads? (it may require SO_REUSEPORT on Linux to divide incoming traffic effective)

**Comment by kanocz** [comment]
It's look like that if we'll change "go p.recvICMP(conn, recv, recvCtx, wg)" in
if conn != nil {
		wg.Add(1)
		go p.recvICMP(conn, recv, recvCtx, wg)
	}

to loop which runs little bit more thread with recvICMP we'll get much better performance for receiving icmp without any other code modification... i'll try this tomorrow

**Pull request closed without merging**
