### PR TITLE
Multi-thread receive of packets

### PR DESCRIPTION
**Pull request by kanocz**
Receive packets in multiply threads

### CODE REVIEW

**Comment by tatsushid** [comment]
Sorry for the late reply. Does it improve receiving packets in large host environment e.g. yours?

**Comment by kanocz** [comment]
Yes it does. On Linux with 24-cpu-core it's now possible to do ping in 48000ip chunks with exact latency returned. It's much better than it was :)

**Comment by tatsushid** [comment]
It merged into 42755b0. Now both send and recv are multiplexed so `procRecv` can be removed and merged into `sendICMP`. After doing it and some more refactoring, I will merge the branch into master.

**Comment by kkirsche** [comment]
Does this fix #14 ?

**Comment by tatsushid** [comment]
@kkirsche, it should be. I will do more work on this.

**Comment by hackstoic** [comment]
I ping 800 ips  every 1 second, my machine has 4 core cpu and 16G memory , and it occured packets loss when pinging some hosts .  

tcpdump results show that the host's  echo reply packet actually arrived . 

is there  something wrong when i use the fastping package?

below is my code: 

`package cping

import (
        "fmt"
        "github.com/kanocz/go-fastping"
        "log"
        "net"
        "os"
        "syscall"
        "os/signal"
        "strings"
        "time"
)

var pingIP string = ""
var rowcounter int
var recvcounter int 
var maxPingCount int = 999 // maxPingCount should be greater than Count, or it will ping at maxPingCount, then quit
var ipList []string
var pingStats map[string]stats

type milliDuration time.Duration

func (hd milliDuration) String() string {
        milliseconds := time.Duration(hd).Nanoseconds()
        milliseconds = milliseconds / 1000000
        return fmt.Sprintf("%d", milliseconds)
}

func (hd milliDuration) Int() int {
        milliseconds := time.Duration(hd).Nanoseconds()
        milliseconds = milliseconds / 1000000
        return int(milliseconds)
}

type stats struct {
        min   int
        max   int
        avg   int
        count int
        rtts  []int
}

type PingStat struct {
        Pktloss  float32
        Resptime int
}

type response struct {
        addr *net.IPAddr
        rtt  time.Duration
}

func checkHostErr(host string, err error) {
        if err != nil {
                log.Fatal(host, ": ", err)
        }
}

func GoPing(ipListInput []string, hosts map[string]string)  {
        pingIP = strings.Join(ipListInput, " ")
        pingStats = make(map[string]stats, 1000)
        result := make(map[string]string, 1000)
        onRecv, onIdle := make(chan _response, len(ipListInput)), make(chan bool)
        c := make(chan os.Signal, 1)
        signal.Notify(c, os.Interrupt)
        signal.Notify(c, syscall.SIGTERM)
        p := fastping.NewPinger()
        p.MaxRTT = time.Second
        for _, host := range strings.Fields(pingIP) {
                ra, err := net.ResolveIPAddr("ip:icmp", host)
                checkHostErr(host, err)
                p.AddIPAddr(ra)
                ipList = append(ipList, ra.String())
                result[host] =  "null"
        }
        p.OnRecv = func(addr *net.IPAddr, rtt time.Duration) {
                onRecv <- &response{addr: addr, rtt: rtt}
        }
        p.OnIdle = func(_ map[string]_net.IPAddr) {
                onIdle <- true
        }
        //p.Debug = g.Config().Debug
        p.RunLoop()
loop:
        for {
                select {
                case <-c:
                        fmt.Println("get interrupted")
                        break loop
                case res := <-onRecv:
                        addr_string := res.addr.String()
                        //log.Println("Receive echo reply from ", addr_string)
                        recvcounter ++
                        if _, ok := result[addr_string]; ok {
                                result[addr_string] = milliDuration(res.rtt).String()
                                stats := pingStats[addr_string]
                                stats.rtts = append(stats.rtts, milliDuration(res.rtt).Int())
                                pingStats[addr_string] = stats
                        }
                case <-onIdle:
                        log.Println("---------------------------------------------")
                        log.Println("The total ip to ping is ", len(ipList))
                        log.Println("The receive counter is ", recvcounter)
                        // reset packet  receive counter 
                        recvcounter = 0
                        for _, ip := range ipList {
                                if result[ip] == "null" {
                                        log.Printf("Can not receive reply from %s at this turn \n", ip)
                                        stats := pingStats[ip]
                                        stats.rtts = append(stats.rtts, -1)
                                        pingStats[ip] = stats
                                }
                                // reset result of every turn
                                result[ip] = "null"
                        }
                        rowcounter++
        //              log.Println(pingStats)
                        if rowcounter == maxPingCount {
                                break loop
                        }
                        if (rowcounter > 0) && (rowcounter%g.Config().Count == 0) {
                                for hostname, ip := range hosts {
                                        s := GetHostIpStat(ip)
                                        fmt.Println(s)
                                }
                                // reset pingStats , rowcounter , recvcounter
                                pingStats = make(map[string]stats, 1000)
                                rowcounter = 0
                        }
                        log.Println("=============================================")
                case <-p.Done():
                        if err := p.Err(); err != nil {
                                fmt.Println("Ping failed:", err)
                        }
                        break loop
                }
        }
        signal.Stop(c)
        p.Stop()
}

func GetHostIpStat(host string) *PingStat {
        stat := pingStats[host]
        ploss := 0
        for _, entry := range stat.rtts[0:rowcounter] {
                if entry != -1 {
                        if entry > stat.max {
                                stat.max = entry
                        }
                        if entry < stat.min {
                                stat.min = entry
                        }
                        stat.avg = stat.avg + entry
                } else {
                        ploss++
                }
        }
        if ploss == rowcounter {
                stat.min = -1
                stat.max = -1
                stat.avg = -1
        } else {
                stat.avg = stat.avg / (rowcounter - ploss)
        }
        plosspct := float32(ploss) / float32(rowcounter) \* 100
        if g.Config().Debug {
                log.Printf("%-38s: %4d %4d %4d %5d/%d (%.2f%%)\n", host, stat.min, stat.max, stat.avg, ploss, rowcounter, plosspct)
        }
        return &PingStat{
                Pktloss:  plosspct,
                Resptime: stat.avg,
        }
}

`

**Comment by hackstoic** [comment]
@kanocz  i use your fork of the fastping. you say that you test 48000ip ping with exact result. could you tell me how to get it ?  looking forward to your reply . thank a lot. 

@others or others  has the  answer?

**Comment by kanocz** [comment]
@hackstoic I'm using much more modified (stripped down) version of go-fastping in live projects (most mutex locks removed, ipv6 support removed, only single run supported, single context, so no re-run until finished and so on). If you need I can little bit polish it and push commit to my repo

**Comment by hackstoic** [comment]
@kanocz  yes . I appreciate that if you push the new commit. I also use the code in live projects which need to ping more than 20, 000 ips and collect the packet loss and response time .   Thank you again.

**Comment by hackstoic** [comment]
@kanocz  i suffer the incollect loss rate these day . but i can't find the root cause.  i refactor my code  but it still don't receive the icmp reply sometime. (i made tcpdumps again and again, and be sure that the icmp reply had actually arrived).

**Comment by hackstoic** [comment]
@kanocz  paste my code here. (i hope it won't  annoy you )

package cping

import (

```
"fmt"

"github.com/kanocz/go-fastping"

"github.com/zabbix_ping/g"

"log"

"net"

"os"

"syscall"

"os/signal"

"strings"

"time"
```

)

var pingIP string = ""

var rowcounter int

var recvcounter int

var maxPingCount int = 999 // maxPingCount should be greater than Count, or it will ping at maxPingCount, then quit

var ipList []string

var pingStats map[string]stats

type milliDuration time.Duration

func (hd milliDuration) String() string {

```
milliseconds := time.Duration(hd).Nanoseconds()

milliseconds = milliseconds / 1000000

return fmt.Sprintf("%d", milliseconds)
```

}

func (hd milliDuration) Int() int {

```
milliseconds := time.Duration(hd).Nanoseconds()

milliseconds = milliseconds / 1000000

return int(milliseconds)
```

}

type stats struct {

```
min   int

max   int

avg   int

count int

rtts  []int
```

}

type response struct {

```
addr *net.IPAddr

rtt  time.Duration
```

}

func checkHostErr(host string, err error) {

```
if err != nil {

    log.Fatal(host, ": ", err)

}
```

}

func GoPing(ipListInput []string, hosts map[string]string)  {

```
pingIP = strings.Join(ipListInput, " ")

pingStats = make(map[string]stats, 1000)

result := make(map[string]string, 1000)

onRecv, onIdle := make(chan *response, len(ipListInput)), make(chan bool)

c := make(chan os.Signal, 1)

signal.Notify(c, os.Interrupt)

signal.Notify(c, syscall.SIGTERM)

p := fastping.NewPinger()

p.MaxRTT = time.Second * time.Duration(g.Config().Timeout)

for _, host := range strings.Fields(pingIP) {

    ra, err := net.ResolveIPAddr("ip:icmp", host)

    checkHostErr(host, err)

    p.AddIPAddr(ra)

    ipList = append(ipList, ra.String())

    result[host] =  "null"

}

p.OnRecv = func(addr *net.IPAddr, rtt time.Duration) {

    onRecv <- &response{addr: addr, rtt: rtt}

}

p.OnIdle = func(_ map[string]*net.IPAddr) {

    onIdle <- true

}

p.Debug = g.Config().Debug

p.RunLoop()
```

loop:

```
for {

    select {

    case <-c:

        log.Println("get interrupted")

        break loop

    case res := <-onRecv:

        addr_string := res.addr.String()

        //log.Println("Receive echo reply from ", addr_string)

        recvcounter ++

        if _, ok := result[addr_string]; ok {

            result[addr_string] = milliDuration(res.rtt).String()

            stats := pingStats[addr_string]

            stats.rtts = append(stats.rtts, milliDuration(res.rtt).Int())

            pingStats[addr_string] = stats

        }

    case <-onIdle:

        log.Println("---------------------------------------------")

        log.Println("The total ip to ping is ", len(ipList))

        log.Println("The receive counter is ", recvcounter)

        // reset packet  receive counter

        recvcounter = 0

        for _, ip := range ipList {

            if result[ip] == "null" {

                log.Printf("Can not receive reply from %s at this turn \n", ip)

                stats := pingStats[ip]

                stats.rtts = append(stats.rtts, -1)

                pingStats[ip] = stats

            }

            // reset result of every turn

            result[ip] = "null"

        }

        rowcounter++

//        log.Println(pingStats)

        if rowcounter == maxPingCount {

            break loop

        }

        if (rowcounter > 0) && (rowcounter%g.Config().Count == 0) {

            ZabbixSender(hosts)

            // reset pingStats , rowcounter , recvcounter

            pingStats = make(map[string]stats, 1000)

            rowcounter = 0

        }

        log.Println("=============================================")

    case <-p.Done():

        if err := p.Err(); err != nil {

            fmt.Println("Ping failed:", err)

        }

        break loop

    }

}

signal.Stop(c)

p.Stop()
```

}

**Comment by kanocz** [comment]
Sorry, I'm little too busy at main work, but I hope to publish my version of go-fastping by the end of the week. I have removed almost all using of mutex and so on, so it several times less  syscalls to kernel and synchronizations between processor cores.

**Comment by hackstoic** [comment]
@kanocz  Thanks. I can understand. And I will keep watch to your repo and  try to solve this problem by myself at the same time.

**Comment by kanocz** [comment]
@hackstoic sorry, it takes a little bit more time to prepare patch that can be publishes :-(
but please note that I've removed many functions like RunLoop(), any preparation have to be done in one thread + no controls about any modification of settings during the ping (this will end with panic)
this is little bit cleaned up version compared to that I'm using in real life

**Pull request closed without merging**
